# Problem Statement
When processing Excel files, we would like to see a quick snapshot of differences between any 2 Excel files.

# Solution
This work book exports a difference Excel file indicating the differences between the two Excel inputs.

# Code
### 1. Specify inputs

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
first_excel = Path('/Volumes/RadReportsAdmin/CR Folder/Critical Results - March 2025.xlsx')
second_excel = Path('/Users/maiyn/Work/Packages/RAD_funcs/Processed - Critical Results - March 2025.xlsx')

df1 = pd.read_excel(first_excel)
df2 = pd.read_excel(second_excel)

In [3]:
# Get diff
common_column = 'Sort#'
merged = df1.merge(df2, how='outer', on='Sort#', suffixes=('_original', '_processed'))

In [4]:
# Get relevant diff columns
relevant_column = 'CR called Date/Time'
diff = merged[merged[f'{relevant_column}_original'] != merged[f'{relevant_column}_processed']]
diff

,Sort#,Report Text_original,Report Created Date/Time_original,CR called Date/Time_original,Minutes From\nCreated to Called_original,Called <\n31 minutes_original,Called < \n61 minutes_original,Unnamed: 7,%Under 31 min_original,0.821293,...,Report Created Date/Time_processed,CR called Date/Time_processed,Minutes From\nCreated to Called_processed,Called <\n31 minutes_processed,Called < \n61 minutes_processed,Note,%Under 31 min_processed,0.839218,%Under 61 min_processed,0.939707
11,12,EXAM: CT PULMONARY ANGIOGRAPHY _x000D_\n_x000D...,2025-03-11 13:00:19,2025-03-11 13:08:00,7.683333,1,1,NaN,NaN,NaN,...,2025-03-11 13:00:19,2025-03-11 00:00:00,-780.32,1,1,"Time likely not parsed, Big difference in days...",NaN,NaN,NaN,NaN
66,67,EXAM: XR PORTABLE CHEST _x000D_\n_x000D_\nINDI...,2025-03-15 02:27:05,2025-03-15 02:29:00,1.916667,1,1,NaN,NaN,NaN,...,2025-03-15 02:27:05,2025-03-15 02:28:00,0.92,1,1,NaN,NaN,NaN,NaN,NaN
70,71,EXAM: XR PORTABLE CHEST _x000D_\n_x000D_\nINDI...,2025-03-11 11:05:27,2025-03-11 11:10:00,4.550000,1,1,NaN,NaN,NaN,...,2025-03-11 11:05:27,2025-03-11 01:10:00,-595.45,1,1,"Date taken from Report Created, Big difference...",NaN,NaN,NaN,NaN
75,76,EXAM: XR PORTABLE CHEST _x000D_\n_x000D_\nINDI...,2025-03-07 14:53:26,2025-03-07 15:24:00,30.566667,1,1,NaN,NaN,NaN,...,2025-03-07 14:53:26,2025-03-07 14:48:00,-5.43,1,1,NaN,NaN,NaN,NaN,NaN
78,79,EXAM: XR CHEST PA AND LATERAL _x000D_\n_x000D_...,2025-03-07 14:46:36,2025-03-07 14:50:00,3.400000,1,1,NaN,NaN,NaN,...,2025-03-07 14:46:36,2025-03-07 00:00:00,-886.60,1,1,"Time likely not parsed, Big difference in days...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,1696,"EXAM: CT ABDOMEN AND PELVIS WITH IV CONTRAST, ...",2025-02-04 23:59:36,2025-02-05 00:41:00,41.400000,0,1,NaN,NaN,NaN,...,2025-02-04 23:59:36,2025-02-04 00:00:00,-1439.60,1,1,"Time likely not parsed, Big difference in days...",NaN,NaN,NaN,NaN
1702,1703,EXAM: CTA NECK W AND OR WO CONTRAST_x000D_\nEX...,2025-02-02 18:58:01,2025-02-02 19:21:00,22.983333,1,1,NaN,NaN,NaN,...,2025-02-02 18:58:01,2025-02-02 19:13:00,14.98,1,1,NaN,NaN,NaN,NaN,NaN
1703,1704,EXAM: CTA NECK W AND OR WO CONTRAST_x000D_\nEX...,2025-02-02 18:58:01,2025-02-02 19:21:00,22.983333,1,1,NaN,NaN,NaN,...,2025-02-02 18:58:01,2025-02-02 19:13:00,14.98,1,1,NaN,NaN,NaN,NaN,NaN
1814,1815,EXAM: CTA NECK W AND OR WO CONTRAST\nEXAM: CTA...,2025-03-28 08:28:37,2025-03-28 08:40:00,11.383333,1,1,NaN,NaN,NaN,...,2025-03-28 08:28:37,2025-03-28 00:00:00,-508.62,1,1,"Time likely not parsed, Big difference in minutes",NaN,NaN,NaN,NaN
1815,1816,EXAM: CTA NECK W AND OR WO CONTRAST\nEXAM: CTA...,2025-03-28 08:28:37,2025-03-28 09:11:00,42.383333,0,1,NaN,NaN,NaN,...,2025-03-28 08:28:37,2025-03-28 00:00:00,-508.62,1,1,"Time likely not parsed, Big difference in minutes",NaN,NaN,NaN,NaN

In [5]:
# Define columns to output
columns = [
'Sort#', 
'Report Created Date/Time_original', 
'CR called Date/Time_original',	
'CR called Date/Time_processed', 
"Minutes From\nCreated to Called_original", 
"Minutes From\nCreated to Called_processed", 
"Note",
"Report Text_processed"
]
diff[columns].to_excel('Diff.xlsx', index=False)